const josh = [
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-03-30 13:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "DET",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/116.png",
    "PA": 7,
    "AB": 6,
    "H": 3,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 1,
    "TB": 3,
    "RBI": 3
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-01 13:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "DET",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/116.png",
    "PA": 4,
    "AB": 4,
    "H": 2,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 3,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-01 18:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "DET",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/116.png",
    "PA": 4,
    "AB": 3,
    "H": 1,
    "HR": 0,
    "BB": 1,
    "K": 2,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-02 13:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIN",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/142.png",
    "PA": 4,
    "AB": 3,
    "H": 1,
    "HR": 0,
    "BB": 1,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-04 18:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIN",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/142.png",
    "PA": 4,
    "AB": 4,
    "H": 1,
    "HR": 1,
    "BB": 0,
    "K": 2,
    "HBP": 0,
    "SF": 0,
    "TB": 4,
    "RBI": 2
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-05 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CIN",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/113.png",
    "PA": 4,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-06 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CIN",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/113.png",
    "PA": 5,
    "AB": 2,
    "H": 0,
    "HR": 0,
    "BB": 3,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-07 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CIN",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/113.png",
    "PA": 4,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-08 13:35:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CIN",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/113.png",
    "PA": 4,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-10 15:20:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CHC",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/112.png",
    "PA": 5,
    "AB": 5,
    "H": 2,
    "HR": 0,
    "BB": 0,
    "K": 2,
    "HBP": 0,
    "SF": 0,
    "TB": 3,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-11 21:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CHC",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/112.png",
    "PA": 4,
    "AB": 3,
    "H": 0,
    "HR": 0,
    "BB": 1,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-12 15:20:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CHC",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/112.png",
    "PA": 5,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 1,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 2,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-13 19:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIA",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/146.png",
    "PA": 4,
    "AB": 4,
    "H": 0,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-14 19:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIA",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/146.png",
    "PA": 4,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-15 13:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIA",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/146.png",
    "PA": 5,
    "AB": 5,
    "H": 3,
    "HR": 0,
    "BB": 0,
    "K": 2,
    "HBP": 0,
    "SF": 0,
    "TB": 4,
    "RBI": 3
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-16 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "COL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/115.png",
    "PA": 4,
    "AB": 4,
    "H": 0,
    "HR": 0,
    "BB": 0,
    "K": 3,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-17 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "COL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/115.png",
    "PA": 4,
    "AB": 4,
    "H": 0,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-18 12:35:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "COL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/115.png",
    "PA": 5,
    "AB": 5,
    "H": 2,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 3,
    "RBI": 3
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-19 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "PHI",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/143.png",
    "PA": 4,
    "AB": 4,
    "H": 0,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-20 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "PHI",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/143.png",
    "PA": 4,
    "AB": 3,
    "H": 0,
    "HR": 0,
    "BB": 1,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-21 16:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "PHI",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/143.png",
    "PA": 3,
    "AB": 3,
    "H": 0,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-22 13:35:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "PHI",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/143.png",
    "PA": 1,
    "AB": 1,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 3,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-25 16:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "DET",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/116.png",
    "PA": 5,
    "AB": 5,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 2,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 2
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-25 20:00:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "DET",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/116.png",
    "PA": 5,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 1,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-26 12:35:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "DET",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/116.png",
    "PA": 4,
    "AB": 4,
    "H": 0,
    "HR": 0,
    "BB": 0,
    "K": 2,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-27 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "STL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/138.png",
    "PA": 5,
    "AB": 5,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-28 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "STL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/138.png",
    "PA": 4,
    "AB": 3,
    "H": 1,
    "HR": 0,
    "BB": 1,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-29 13:35:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "STL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/138.png",
    "PA": 4,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-04-30 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "WSH",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/120.png",
    "PA": 4,
    "AB": 4,
    "H": 0,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-01 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "WSH",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/120.png",
    "PA": 4,
    "AB": 3,
    "H": 2,
    "HR": 0,
    "BB": 1,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 3,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-02 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "WSH",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/120.png",
    "PA": 4,
    "AB": 3,
    "H": 0,
    "HR": 0,
    "BB": 1,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-03 13:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "WSH",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/120.png",
    "PA": 1,
    "AB": 1,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-04 20:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/158.png",
    "PA": 5,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 1,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-05 19:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/158.png",
    "PA": 4,
    "AB": 3,
    "H": 0,
    "HR": 0,
    "BB": 1,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-06 14:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/158.png",
    "PA": 5,
    "AB": 4,
    "H": 1,
    "HR": 1,
    "BB": 1,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 4,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-08 20:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CWS",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/145.png",
    "PA": 5,
    "AB": 4,
    "H": 2,
    "HR": 0,
    "BB": 1,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 4,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-09 14:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CWS",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/145.png",
    "PA": 4,
    "AB": 2,
    "H": 1,
    "HR": 0,
    "BB": 2,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-11 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "SF",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/137.png",
    "PA": 5,
    "AB": 5,
    "H": 1,
    "HR": 1,
    "BB": 0,
    "K": 2,
    "HBP": 0,
    "SF": 0,
    "TB": 4,
    "RBI": 2
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-12 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "SF",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/137.png",
    "PA": 4,
    "AB": 3,
    "H": 2,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 1,
    "TB": 3,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-13 13:35:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "SF",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/137.png",
    "PA": 4,
    "AB": 3,
    "H": 0,
    "HR": 0,
    "BB": 1,
    "K": 3,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-15 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CWS",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/145.png",
    "PA": 4,
    "AB": 4,
    "H": 2,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 4,
    "RBI": 3
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-16 12:35:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CWS",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/145.png",
    "PA": 1,
    "AB": 1,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-17 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "SD",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/135.png",
    "PA": 4,
    "AB": 4,
    "H": 2,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 2,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-18 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "SD",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/135.png",
    "PA": 5,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 1,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 2,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-19 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "SD",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/135.png",
    "PA": 4,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 3,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-20 13:35:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "SD",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/135.png",
    "PA": 5,
    "AB": 5,
    "H": 0,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-22 19:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CIN",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/113.png",
    "PA": 4,
    "AB": 3,
    "H": 0,
    "HR": 0,
    "BB": 1,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-23 19:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CIN",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/113.png",
    "PA": 6,
    "AB": 5,
    "H": 1,
    "HR": 0,
    "BB": 1,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-24 12:35:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CIN",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/113.png",
    "PA": 1,
    "AB": 1,
    "H": 0,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-25 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "STL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/138.png",
    "PA": 4,
    "AB": 3,
    "H": 2,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 1,
    "TB": 2,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-26 16:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "STL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/138.png",
    "PA": 4,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 2,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-27 13:35:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "STL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/138.png",
    "PA": 4,
    "AB": 4,
    "H": 0,
    "HR": 0,
    "BB": 0,
    "K": 2,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-28 13:35:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CHC",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/112.png",
    "PA": 3,
    "AB": 3,
    "H": 0,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-29 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CHC",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/112.png",
    "PA": 5,
    "AB": 5,
    "H": 2,
    "HR": 0,
    "BB": 0,
    "K": 2,
    "HBP": 0,
    "SF": 0,
    "TB": 2,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-30 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CHC",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/112.png",
    "PA": 4,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-05-31 19:15:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "STL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/138.png",
    "PA": 5,
    "AB": 4,
    "H": 1,
    "HR": 1,
    "BB": 1,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 4,
    "RBI": 2
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-06-01 20:15:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "STL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/138.png",
    "PA": 4,
    "AB": 1,
    "H": 0,
    "HR": 0,
    "BB": 2,
    "K": 0,
    "HBP": 0,
    "SF": 1,
    "TB": 0,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-06-02 14:15:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "STL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/138.png",
    "PA": 4,
    "AB": 4,
    "H": 0,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-06-03 14:15:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "STL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/138.png",
    "PA": 4,
    "AB": 4,
    "H": 0,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-06-05 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "LAD",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/119.png",
    "PA": 4,
    "AB": 4,
    "H": 0,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-06-06 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "LAD",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/119.png",
    "PA": 1,
    "AB": 1,
    "H": 0,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-06-07 12:35:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "LAD",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/119.png",
    "PA": 5,
    "AB": 5,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 2,
    "HBP": 0,
    "SF": 0,
    "TB": 2,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-06-08 15:20:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CHC",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/112.png",
    "PA": 1,
    "AB": 1,
    "H": 0,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-06-09 15:20:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CHC",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/112.png",
    "PA": 3,
    "AB": 2,
    "H": 0,
    "HR": 0,
    "BB": 1,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-06-10 15:20:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CHC",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/112.png",
    "PA": 4,
    "AB": 1,
    "H": 1,
    "HR": 0,
    "BB": 3,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-06-11 21:40:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "ARI",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/109.png",
    "PA": 4,
    "AB": 1,
    "H": 0,
    "HR": 0,
    "BB": 3,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-06-12 21:40:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "ARI",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/109.png",
    "PA": 5,
    "AB": 5,
    "H": 3,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 5,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-06-13 15:40:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "ARI",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/109.png",
    "PA": 4,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 2,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-06-15 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CIN",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/113.png",
    "PA": 3,
    "AB": 3,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-06-16 16:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CIN",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/113.png",
    "PA": 4,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 2,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-06-17 13:35:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CIN",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/113.png",
    "PA": 4,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-06-18 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/158.png",
    "PA": 3,
    "AB": 3,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-06-19 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/158.png",
    "PA": 4,
    "AB": 3,
    "H": 0,
    "HR": 0,
    "BB": 1,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-06-21 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "ARI",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/109.png",
    "PA": 4,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-06-22 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "ARI",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/109.png",
    "PA": 1,
    "AB": 0,
    "H": 0,
    "HR": 0,
    "BB": 1,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-06-23 16:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "ARI",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/109.png",
    "PA": 4,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-06-24 13:35:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "ARI",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/109.png",
    "PA": 3,
    "AB": 3,
    "H": 2,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 2,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-06-25 19:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "NYM",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/121.png",
    "PA": 5,
    "AB": 4,
    "H": 1,
    "HR": 1,
    "BB": 1,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 4,
    "RBI": 2
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-06-26 19:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "NYM",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/121.png",
    "PA": 1,
    "AB": 1,
    "H": 0,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-06-27 19:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "NYM",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/121.png",
    "PA": 5,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 1,
    "TB": 1,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-06-29 23:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "SD",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/135.png",
    "PA": 5,
    "AB": 5,
    "H": 2,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 3,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-06-30 23:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "SD",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/135.png",
    "PA": 4,
    "AB": 3,
    "H": 1,
    "HR": 0,
    "BB": 1,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-07-01 17:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "SD",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/135.png",
    "PA": 5,
    "AB": 3,
    "H": 1,
    "HR": 0,
    "BB": 2,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-07-02 23:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "LAD",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/119.png",
    "PA": 1,
    "AB": 1,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-07-03 23:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "LAD",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/119.png",
    "PA": 3,
    "AB": 3,
    "H": 0,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-07-04 21:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "LAD",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/119.png",
    "PA": 1,
    "AB": 1,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-07-06 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "PHI",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/143.png",
    "PA": 5,
    "AB": 5,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 2,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-07-07 16:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "PHI",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/143.png",
    "PA": 4,
    "AB": 4,
    "H": 0,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-07-08 13:35:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "PHI",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/143.png",
    "PA": 4,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 2,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-07-10 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "WSH",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/120.png",
    "PA": 4,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-07-11 12:35:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "WSH",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/120.png",
    "PA": 3,
    "AB": 3,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-07-12 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/158.png",
    "PA": 4,
    "AB": 1,
    "H": 0,
    "HR": 0,
    "BB": 3,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-07-13 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/158.png",
    "PA": 4,
    "AB": 4,
    "H": 4,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 7,
    "RBI": 2
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-07-14 12:35:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/158.png",
    "PA": 4,
    "AB": 3,
    "H": 1,
    "HR": 0,
    "BB": 1,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-07-14 20:00:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/158.png",
    "PA": 3,
    "AB": 2,
    "H": 0,
    "HR": 0,
    "BB": 1,
    "K": 2,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-07-15 13:35:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/158.png",
    "PA": 5,
    "AB": 5,
    "H": 2,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 3,
    "RBI": 2
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-07-20 19:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CIN",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/113.png",
    "PA": 5,
    "AB": 3,
    "H": 0,
    "HR": 0,
    "BB": 2,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-07-21 19:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CIN",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/113.png",
    "PA": 4,
    "AB": 4,
    "H": 4,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 5,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-07-22 13:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CIN",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/113.png",
    "PA": 5,
    "AB": 5,
    "H": 2,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 2,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-07-23 19:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CLE",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/114.png",
    "PA": 3,
    "AB": 3,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-07-24 19:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CLE",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/114.png",
    "PA": 4,
    "AB": 4,
    "H": 2,
    "HR": 1,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 5,
    "RBI": 2
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-07-25 13:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CLE",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/114.png",
    "PA": 4,
    "AB": 3,
    "H": 0,
    "HR": 0,
    "BB": 1,
    "K": 2,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-07-26 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "NYM",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/121.png",
    "PA": 4,
    "AB": 4,
    "H": 0,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-07-27 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "NYM",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/121.png",
    "PA": 1,
    "AB": 1,
    "H": 0,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-08-08 16:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "COL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/115.png",
    "PA": 5,
    "AB": 4,
    "H": 0,
    "HR": 0,
    "BB": 1,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-08-09 23:15:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "SF",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/137.png",
    "PA": 5,
    "AB": 4,
    "H": 1,
    "HR": 1,
    "BB": 1,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 4,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-08-10 23:15:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "SF",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/137.png",
    "PA": 5,
    "AB": 5,
    "H": 3,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 4,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-08-11 22:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "SF",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/137.png",
    "PA": 4,
    "AB": 4,
    "H": 1,
    "HR": 1,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 4,
    "RBI": 3
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-08-12 17:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "SF",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/137.png",
    "PA": 4,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 2,
    "HBP": 0,
    "SF": 0,
    "TB": 2,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-08-14 20:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIN",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/142.png",
    "PA": 4,
    "AB": 2,
    "H": 1,
    "HR": 0,
    "BB": 2,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-08-15 13:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIN",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/142.png",
    "PA": 5,
    "AB": 4,
    "H": 0,
    "HR": 0,
    "BB": 1,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-08-16 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CHC",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/112.png",
    "PA": 3,
    "AB": 3,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-08-17 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CHC",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/112.png",
    "PA": 3,
    "AB": 3,
    "H": 0,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-08-18 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CHC",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/112.png",
    "PA": 4,
    "AB": 3,
    "H": 1,
    "HR": 0,
    "BB": 1,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-08-19 13:35:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CHC",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/112.png",
    "PA": 5,
    "AB": 4,
    "H": 0,
    "HR": 0,
    "BB": 1,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-08-20 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "ATL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/144.png",
    "PA": 4,
    "AB": 3,
    "H": 1,
    "HR": 0,
    "BB": 1,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-08-21 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "ATL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/144.png",
    "PA": 4,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-08-22 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "ATL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/144.png",
    "PA": 3,
    "AB": 2,
    "H": 0,
    "HR": 0,
    "BB": 1,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-08-24 20:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/158.png",
    "PA": 1,
    "AB": 1,
    "H": 0,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-08-25 19:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/158.png",
    "PA": 5,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 1,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-08-28 20:15:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "STL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/138.png",
    "PA": 3,
    "AB": 2,
    "H": 1,
    "HR": 0,
    "BB": 1,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 2,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-08-29 20:15:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "STL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/138.png",
    "PA": 4,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-08-30 19:15:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "STL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/138.png",
    "PA": 4,
    "AB": 2,
    "H": 1,
    "HR": 0,
    "BB": 2,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 2,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-08-31 19:35:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "ATL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/144.png",
    "PA": 4,
    "AB": 3,
    "H": 0,
    "HR": 0,
    "BB": 1,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-09-01 19:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "ATL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/144.png",
    "PA": 4,
    "AB": 4,
    "H": 0,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-09-02 17:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "ATL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/144.png",
    "PA": 3,
    "AB": 2,
    "H": 0,
    "HR": 0,
    "BB": 1,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-09-03 13:35:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CIN",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/113.png",
    "PA": 4,
    "AB": 4,
    "H": 0,
    "HR": 0,
    "BB": 0,
    "K": 3,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-09-07 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIA",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/146.png",
    "PA": 4,
    "AB": 3,
    "H": 1,
    "HR": 1,
    "BB": 1,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 4,
    "RBI": 2
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-09-08 13:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIA",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/146.png",
    "PA": 4,
    "AB": 2,
    "H": 1,
    "HR": 1,
    "BB": 2,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 4,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-09-10 20:15:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "STL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/138.png",
    "PA": 5,
    "AB": 5,
    "H": 3,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 4,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-09-11 20:15:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "STL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/138.png",
    "PA": 4,
    "AB": 4,
    "H": 2,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 3,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-09-12 13:15:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "STL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/138.png",
    "PA": 4,
    "AB": 3,
    "H": 1,
    "HR": 0,
    "BB": 1,
    "K": 2,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-09-14 20:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/158.png",
    "PA": 4,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 2,
    "HBP": 0,
    "SF": 0,
    "TB": 2,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-09-15 19:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/158.png",
    "PA": 4,
    "AB": 3,
    "H": 1,
    "HR": 0,
    "BB": 1,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-09-16 14:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/158.png",
    "PA": 4,
    "AB": 2,
    "H": 0,
    "HR": 0,
    "BB": 2,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-09-17 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "KC",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/118.png",
    "PA": 5,
    "AB": 4,
    "H": 2,
    "HR": 0,
    "BB": 1,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 2,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-09-18 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "KC",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/118.png",
    "PA": 5,
    "AB": 4,
    "H": 2,
    "HR": 0,
    "BB": 1,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 3,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-09-19 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "KC",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/118.png",
    "PA": 4,
    "AB": 4,
    "H": 2,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 3,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-09-21 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/158.png",
    "PA": 4,
    "AB": 4,
    "H": 2,
    "HR": 1,
    "BB": 0,
    "K": 2,
    "HBP": 0,
    "SF": 0,
    "TB": 5,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-09-22 19:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/158.png",
    "PA": 4,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-09-23 13:35:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "MIL",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/158.png",
    "PA": 4,
    "AB": 4,
    "H": 0,
    "HR": 0,
    "BB": 0,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-09-24 21:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CHC",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/112.png",
    "PA": 5,
    "AB": 4,
    "H": 1,
    "HR": 0,
    "BB": 1,
    "K": 2,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-09-25 21:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CHC",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/112.png",
    "PA": 5,
    "AB": 3,
    "H": 0,
    "HR": 0,
    "BB": 2,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 1
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-09-26 21:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CHC",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/112.png",
    "PA": 2,
    "AB": 1,
    "H": 0,
    "HR": 0,
    "BB": 1,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-09-27 21:05:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CHC",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/112.png",
    "PA": 4,
    "AB": 3,
    "H": 0,
    "HR": 0,
    "BB": 1,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-09-28 18:40:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CIN",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/113.png",
    "PA": 5,
    "AB": 5,
    "H": 1,
    "HR": 0,
    "BB": 0,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 1,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-09-29 16:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CIN",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/113.png",
    "PA": 4,
    "AB": 3,
    "H": 0,
    "HR": 0,
    "BB": 1,
    "K": 1,
    "HBP": 0,
    "SF": 0,
    "TB": 0,
    "RBI": 0
  },
  {
    "playerId": 605137,
    "fullName": "Josh Bell",
    "playerImage": "https://mlb.mlb.com/images/players/mugshot/ph_605137.jpg",
    "gameDate": "2018-09-30 15:10:00",
    "team": "PIT",
    "teamImage": "http://static.trumedianetworks.com/images/mlb/teams/134.png",
    "opponent": "CIN",
    "opponentImage": "http://static.trumedianetworks.com/images/mlb/teams/113.png",
    "PA": 5,
    "AB": 4,
    "H": 1,
    "HR": 1,
    "BB": 1,
    "K": 0,
    "HBP": 0,
    "SF": 0,
    "TB": 4,
    "RBI": 1
  }
];

export default josh;
